### ISSUE TITLE
Java sample application failed to start

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/samples#180]
Checking the latest execution of the CI workflows in CircleCI I noticed the sample java app is not starting. see [here](https://app.circleci.com/pipelines/github/buildpacks/samples/315/workflows/7c8a9298-7992-4929-b456-29a0b9fed882/jobs/525)

![Screenshot 2023-12-01 at 3 17 36 PM](https://github.com/buildpacks/samples/assets/1181799/0244d9cb-c57f-40ee-bc61-a0132aa8950b)

I tried t o reproduced the error with the following steps:

1. I built the application image using latest pack version `0.32.1`

```bash
> pack build -B cnbs/sample-builder:jammy -p apps/java-maven circleci-sample
// log messages 
Successfully built image circleci-sample
```

2. I tried to run application using the same docker command we are running on CircleCI

```bash
> docker run -d -p 8080:8080 circleci-sample
5d7aedf1fb00652e9a9ee4ff78050fe061d0100b7ad5580714b485c97b14213d
```

3. The container is not running, so I checked the logs 
```bash
> docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
>  docker logs 5d7aedf1fb00652e9a9ee4ff78050fe061d0100b7ad5580714b485c97b14213d
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/samples_java-maven/jdk/exec.d/jdk.sh': fork/exec /layers/samples_java-maven/jdk/exec.d/jdk.sh: exec format error
```

If I am not wrong the error `fork/exec /layers/samples_java-maven/jdk/exec.d/jdk.sh: exec format error` is thrown because the binary is not compatible with the host architecture.

**Comment by AidanDelaney** [comment]
I think we're using the wrong approach to set launch-time env vars.  Rather than providing a `jdk.sh` file to run as an `exec.d` file, we should be writing the env vars to the `env` dir.  The proposed change uses https://github.com/buildpacks/spec/blob/main/buildpack.md#environment-variable-modification-rules

Something like https://github.com/buildpacks/samples/pull/181 might work.  We will also have to do the same in the kotlin-gradle example.

**Comment by AidanDelaney** [comment]
Fixed :)
