### ISSUE TITLE
Deploy Buttons?

### ISSUE THREAD

**Issue by jamesward** [buildpacks/samples#45]
Would it be acceptable to add deploy buttons to the samples?  Like both a Heroku & [Cloud Run deploy button](https://github.com/GoogleCloudPlatform/cloud-run-button).  This would be in the form of a README in https://github.com/buildpack/samples/tree/master/apps/java-maven

Side note, that Heroku Button might not support projects in subdirs.  cc @jkutner

**Comment by jromero** [comment]
This is a very interesting question... 

I think I speak for the majority of the team when I say that we are looking for opportunities to showcase and cross-promote _consumers_ leveraging CNBs. See https://github.com/buildpack/docs/issues/81.

This would certainly be a neat feature but we'd want to make sure it's done with clear intent. Most other repos with with a deploy button would typically include it as a way to demo or otherwise deploy an application worth deploying. Our use case is rather different in that the application is of almost no value but the fact that it can be "auto-magically" built and deployed is what we are trying to spotlight. Finding the right way to express that would be what would motivate us more towards adding deploy buttons in my opinion.

**Comment by dfreilich** [comment]
I tried using it (I used the cloud-run button on the Google samples repo here: https://github.com/GoogleCloudPlatform/buildpack-samples)), and I would've found it useful for the project if it had displayed the build logs, but it didn't seem to do that (maybe that could be configured somewhere?). I don't think it would be the most useful in this context without it though.

**Comment by jamesward** [comment]
Thanks for the feedback.  I've filed an issue to address that: https://github.com/GoogleCloudPlatform/cloud-run-button/issues/190
