### ISSUE TITLE
Need minimal nanoserver-based Windows stack

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/samples#52]
To aid in development and experimentation for users who would like to run CNBs on Windows, we should create a minimal nanoserver-based Windows stack.

### Acceptance Criteria

**Given** I'm targeting a Windows docker daemon
**When** I run `./build-stack.sh nanoserver-1809`
**Then** the image builds
**And** running `docker inspect cnbs/sample-stack-build:nanoserver-1809 | jq` reveals the following values in the image config:
 - Label `io.buildpacks.stack.id` = `io.buildpacks.samples.stacks.nanoserver-1809`
 - Env var `CNB_USER_ID` = `S-1-1-0`
 - Env var `CNB_GROUP_ID` = `S-1-1-0`
 - Env var `CNB_STACK_ID` = `io.buildpacks.samples.stacks.nanoserver-1809`
 - User is `cnb`
 - OS is `windows`

**And** running `docker inspect cnbs/sample-stack-run:nanoserver-1809 | jq` reveals the following values in the image config:
 - Label `io.buildpacks.stack.id` = `io.buildpacks.samples.stacks.nanoserver-1809`
 - Env var `CNB_USER_ID` = `S-1-1-0`
 - Env var `CNB_GROUP_ID` = `S-1-1-0`
 - User is `cnb`
 - OS is `windows`

**Comment by micahyoung** [comment]
After some explorartion, @ameyer-pivotal and I couldn't find a way to set an explicit `SID` ([See "universal well-known security identifier"](https://docs.microsoft.com/en-us/windows/win32/secgloss/u-gly)) when creating a user, since they're [generated](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/security-identifiers#how-security-identifiers-work).

Perhaps it makes sense to start with `CNB_USER_ID=S-1-1-0` and `CNB_GROUP_ID=S-1-1-0` which will be World-permissions ([See "World" in table](https://docs.microsoft.com/en-us/windows/win32/secauthz/well-known-sids)) and hopefully readable by any user we create. We didn't test this yet so implementers should feel free to find alternative approaches.

**Comment by micahyoung** [comment]
Skip Travis setup for Windows now as well, until we get configure for an additional Windows Docker daemon
