### ISSUE TITLE
[java] Support additional maven options : HTTP_PROXY, settings.xml, maven_mirror, dir for maven multi-module

### ISSUE THREAD

**Issue by cmoulliard** [buildpacks/samples#8]
Additional maven options should certainly be implemented as we did here [1] to support to configure : 

- HTTP_PROXY
- User's settings.xml
- MAVEN MIRROR URL
- DIR of the maven module to be compiled

Question : 
- Will it be possible to pass additional parameters to the `mvn compile` command ?
- Will a /bin/develop script be created and extended `/bin/build` script in order to do `mvn test`

[1] https://github.com/fabric8io-images/s2i/blob/master/java/images/centos/s2i/assemble

**Comment by ameyer-pivotal** [comment]
@jromero As a learning maintainer, what's your stance on adding more features to this sample buildpack, versus pointing folks to the more official buildpacks?

**Comment by jromero** [comment]
This is a good set of features but our stance for this samples repo is not to provide fully featured buildpacks. Instead we focus on adding features that display how something could be achieved. 

> Will it be possible to pass additional parameters to the mvn compile command?

Yes, this is possible similar to how the referenced script provides this functionally. A buildpack can take an environment variable to provide additional args. For example, `MAVEN_ARGS_APPEND `. **This might be worth implementing here to show how it's possible.**

> Will a /bin/develop script be created and extended /bin/build script in order to do mvn test

`/bin/develop` has been taken back out of the spec as we continue to research what the set of features should be.

Overall, we would consider accepting PRs for a subset of the configuration elements listed in the original issue but otherwise not planned.

**Comment by jromero** [comment]
I've created an issue strictly for showing the idea of how configuration could be passed to the buildpack. - #65 

Thank you for your feedback.

Feel free to reopen to continue the conversation if you think we are missing some other aspects of your initial comment.
